# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-cockpit" do
  version "0.1.5"

  on_macos do
    on_intel do
      url "https://github.com/pauldub/cc-cockpit/releases/download/v#{version}/cc-cockpit_#{version}_darwin_amd64.tar.gz"
      sha256 "2272d801e9c242788e8d0d6e207a464aca7a41691143e7a82669a7abb33aa35f"
    end
    on_arm do
      url "https://github.com/pauldub/cc-cockpit/releases/download/v#{version}/cc-cockpit_#{version}_darwin_arm64.tar.gz"
      sha256 "678fa28704cb892c0fceb35da2375d695e7267466b2f086536f1748cb9082923"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pauldub/cc-cockpit/releases/download/v#{version}/cc-cockpit_#{version}_linux_amd64.tar.gz"
      sha256 "3406671533fccf962bc1c5d43125c1ec267b6f0f1d58b7d117318b765208999b"
    end
    on_arm do
      url "https://github.com/pauldub/cc-cockpit/releases/download/v#{version}/cc-cockpit_#{version}_linux_arm64.tar.gz"
      sha256 "d11eec046be9197e7cdaac93aefaa2ddfcc79dceb9c5352c20eacf7f98b3f047"
    end
  end

  name "cc-cockpit"
  desc "Terminal PR dashboard for use alongside Claude Code"
  homepage "https://github.com/pauldub/cc-cockpit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-cockpit"

  # No zap stanza required

end
