# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-cockpit" do
  version "0.1.6"

  on_macos do
    on_intel do
      url "https://github.com/pauldub/cc-cockpit/releases/download/v#{version}/cc-cockpit_#{version}_darwin_amd64.tar.gz"
      sha256 "dc83dfcd365a763e703b8551c35fd9379945ee6f2244d56e7db24acd8307a0a0"
    end
    on_arm do
      url "https://github.com/pauldub/cc-cockpit/releases/download/v#{version}/cc-cockpit_#{version}_darwin_arm64.tar.gz"
      sha256 "88aa0d88bd9462128dc28f5d4ee3d3eeadefbea60a134de00d32b82429fc017c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pauldub/cc-cockpit/releases/download/v#{version}/cc-cockpit_#{version}_linux_amd64.tar.gz"
      sha256 "e8f4873ab352328f93e44a1ded3ea078c956d0b0b7eb88a88884a98544252e79"
    end
    on_arm do
      url "https://github.com/pauldub/cc-cockpit/releases/download/v#{version}/cc-cockpit_#{version}_linux_arm64.tar.gz"
      sha256 "07c4793b826258ba1a6d204215766abeb7ed733d4de7b0bd1f7d0abaf5fcca85"
    end
  end

  name "cc-cockpit"
  desc "Terminal PR dashboard for use alongside Claude Code"
  homepage "https://github.com/pauldub/cc-cockpit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-cockpit"

  # No zap stanza required

end
